### ISSUE TITLE
Unable to include partial from file

### ISSUE THREAD

**Issue by mitjafelicijan** [gofiber/template#1]
Hi, I am trying to include partial from a file but seem to have no success.

```go
app := fiber.New()
app.Settings.TemplateEngine = template.Handlebars()
app.Settings.TemplateFolder = "./views"
```

And in the route I do the following

```go
func consoleDefault(c *fiber.Ctx) {
	bind := fiber.Map{
		"name": "John",
		"age":  35,
	}
	if err := c.Render("index.hbs", bind); err != nil {
		c.Status(500).Send(err.Error())
	}
}
```

My index.hbs includes and renders the name variable currently. But the partial is not working. I have tried with relative paths, with and without extensions and no luck.

```handlebars
{{> header.hbs }}
{{ name }}
```

I keep getting this error.

![DeepinScreenshot_select-area_20200406081717](https://user-images.githubusercontent.com/296714/78528209-23c8dc80-77df-11ea-877e-e32e1477adba.png)

I have looked into the Raymond repo and there are no clear examples of how to use it.

Thanks in advance.

**Comment by Fenny** [comment]
@mitjafelicijan, I'm looking into this today. Feel free to join us on telegram https://t.me/gofiber

**Comment by harikt** [comment]
Is this account still valid ? I tried to join it says no account .

**Comment by Fenny** [comment]
Hi @harikt, not sure what you mean with account. Could you clarify?

**Comment by harikt** [comment]
@Fenny I mean the link to telegram seems not working or it says the username is not valid.

**Comment by Fenny** [comment]
Oh it's an old link, we use [Discord](https://gofiber.io/discord) for a while now 👍
