### ISSUE TITLE
Unescape specific bits of output

### ISSUE THREAD

**Issue by lordtottuu** [gofiber/template#101]
How do I output specific sections or variable without them being HTML encoded for safety? I understand the implications of doing this and how I'm exposing myself to XSS etc but I have this one specific bit of code that absolutely needs to be outputted untouched. I checked the [article linked to in the read me](https://curtisvermeeren.github.io/2017/09/14/Golang-Templates-Cheatsheet#creating) and tried using template.HTML but it doesn't seem to be working. 

I appreciate any pointers. Thank you.

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/issues/1224

Use the same solution as in https://medium.com/@arvindsris/how-did-i-unescape-values-in-a-template-using-go-lang-8ce987e8d1f7

**Comment by ReneWerner87** [comment]
hopefully this will help you, if you have no more questions, please close the issue

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/template/tree/html_unescape_example/html#example-with-innerhtml

**Comment by lordtottuu** [comment]
Many thanks, this is exactly what I was looking for.
