### ISSUE TITLE
Django views not rendering

### ISSUE THREAD

**Issue by gregf** [gofiber/template#106]
I have a file like this in side of my project root `views/index.html`. No matter what I try for a path to render the template I get the error `template views/index does not exist`, or something of that nature depending on the path I try passing. I tried the same setup with mustache, and it worked fine.
```
package main

import (
	"embed"
	"log"
	"net/http"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/template/django"
)

//go:embed views/*
var viewsfs embed.FS

func main() {
	engine := django.NewFileSystem(http.FS(viewsfs), ".html")

	app := fiber.New(fiber.Config{
		Views: engine,
	})

	app.Get("/", func(c *fiber.Ctx) error {
		// Render index
		return c.Render("views/index", fiber.Map{
			"Title": "Hello, World!",
		})
	})

	log.Fatal(app.Listen(":3000"))
}

```

**Comment by iredmail** [comment]
Maybe this sample code helps?
https://github.com/gofiber/fiber/tree/master/middleware/filesystem#embed

**Comment by gregf** [comment]
Sorry I ended up figuring it out. It was just a simple path issue.
