### ISSUE TITLE
Recursive .html file parsing ?

### ISSUE THREAD

**Issue by ghost** [gofiber/template#112]
Is it possible to parse html files recursive ? Let's say I have this directory structure:

--templates
-------global
-----------header.html
-----------footer.html
-----------navbar.html
-------pages
-----------index.html
-----------about.html

Right now with html.New("./templates", ".html")

It will error with:   **render: template index does not exist**

It would be nice if the html.New would have a recursive option allowing to parse all templates in all subdirectories

😄

**Comment by MichailVestnik** [comment]
I have the following folder structure:

--templates
-------components
-----------header.html
-----------footer.html
-------pages
-----------index.html
... others

 How do I specify the path to the components In index.html ?
 
 {{template "components/header" .}} - not work
 {{template "../components/header" .}} - not work

Спасибо!

**Comment by gaby** [comment]
I think this can be done using:

```go
html.New("./templates/*", ".html")
```
