### ISSUE TITLE
Update dependent package `logrus` to the latest `1.8.1`

### ISSUE THREAD

**Issue by iredmail** [gofiber/template#115]
Some package still uses old logrus (1.2.0, 1.6.0), might be a good idea to update `logrus` to the latest `1.8.1`.

**Comment by ReneWerner87** [comment]
@iredmail could you update the go.mod file ?

**Comment by iredmail** [comment]
gofiber/template doesn't use logrus directly, so i sent PR for the dependent package:
https://github.com/denis-tingaikin/go-header/pull/10
