### ISSUE TITLE
html Engine cheet-sheet link doesn't work

### ISSUE THREAD

**Issue by zontorai** [gofiber/template#127]
https://github.com/gofiber/template/tree/master/html

Specifically, where it says "click here to preview", it returns a 404 error

**Comment by ReneWerner87** [comment]
Thx for the hint

I found the site https://archive.is/2HksZ

I will make a markdown file from the content and link it.

**Comment by zontorai** [comment]
Thank you. I was actually looking for a clear explanation on how to use
html.Templates. I can't seem to wrap my head around this implementation. :)

**Comment by ReneWerner87** [comment]
should work again now
