### ISSUE TITLE
Ace layouts are rendered as text

### ISSUE THREAD

**Issue by jorgefuertes** [gofiber/template#15]
The inner "embed" template is correct, but the layout is shown as text in browser.
Demo repository at: https://github.com/jorgefuertes/fiber-tests

Thanks.

**Comment by hendratommy** [comment]
This is because of the indentation type. From the main repository examples, looks like they use two space indentation, tried to change the `main.ace` to use two space indentation instead of tab and it working.

**Comment by jorgefuertes** [comment]
Thanks for the solution @hendratommy.

**Comment by hendratommy** [comment]
From this [issue](https://github.com/yosssi/ace/issues/25) seems like it is intended.

**Comment by Fenny** [comment]
Thanks @hendratommy
