### ISSUE TITLE
Django engine Built-in date pipe didn't work

### ISSUE THREAD

**Issue by chobijaeyu** [gofiber/template#150]
hi good day.
I was tring to use date format 
`{{ value|date:"D d M Y" }}`
<img width="571" alt="Screen Shot 2021-12-03 at 11 48 05" src="https://user-images.githubusercontent.com/25117318/144536435-1b8a466c-8cc5-42ed-8921-88916dbbad3c.png">

but rendered html is
`D d M Y`
<img width="166" alt="Screen Shot 2021-12-03 at 11 47 53" src="https://user-images.githubusercontent.com/25117318/144536450-43797143-48dd-4b23-ac0f-114bc389bdae.png">

if remove date pipe
<img width="204" alt="Screen Shot 2021-12-03 at 11 49 15" src="https://user-images.githubusercontent.com/25117318/144536566-937fc7fc-0520-4c6b-9709-8838a1a6c2e1.png">

Is anyway to fix this?
thanks

**Comment by ansidev** [comment]
@chobijaeyu This problem came from your knowledge, please learn and read the documentation: https://pkg.go.dev/time#Time.Format

**Comment by ansidev** [comment]
@ReneWerner87 This is not the project issue, I think it can be closed.

**Comment by ReneWerner87** [comment]
Ok thx

**Comment by chobijaeyu** [comment]
Since use django template,I was read django doc [https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#date](url)

for anyone meet same issue like me.
you should use golang format string `{{r.Date |date:"2006/01/02"}}`
good to know
