### ISSUE TITLE
Template layout handlebars title not replacing properly.

### ISSUE THREAD

**Issue by pateljoel** [gofiber/template#157]
I'm using fiber for a small project and just started with the handlebars example.

I am trying to make the template work with the `<title>{{title}}</title>` tag and it doesn't update instead the source shows `<title></title>` which is what I don't understand.

Help would be appreciated.

[pateljoel/gofiber-templating-title-issue](https://github.com/pateljoel/gofiber-templating-title-issue)

**Comment by ReneWerner87** [comment]
@pateljoel can you try a variable name starting with capital letters in the map and in the template, maybe this is a golang problem, because you can only access variables that start with capital letters

**Comment by pateljoel** [comment]
@ReneWerner87 I have tried using captial letters myself and the title still didn't show up with the title "Homepage" this is the source output:

```html
<html>
  <title></title>
  <body>
    <div>
      <div>index</div>
     </div>
  </body>
</html>
```

**Comment by edimoldovan** [comment]
Hi folks, I am having the same issue. I also tried the capital letters option as well, also without success. Any recommendation on how to make this work?

Alternatively, I will stop using layouts as passing vars in the rest of the templates works fine.
