### ISSUE TITLE
Engine.Load() always return nil

### ISSUE THREAD

**Issue by michail-vestnik** [gofiber/template#163]
**Fiber version**

Latest (2.26.0)

**Issue description**

I tried rereading the templates, but could not find a situation where Load() would work. Then I went to look at the code and found it:

**Code snippet**

![fiber](https://user-images.githubusercontent.com/87961969/152939455-58d1d986-fe2d-493c-9e52-80900eeb5f4a.png)

I deleted these lines and everything worked correctly.

Спасибо!

**Comment by ReneWerner87** [comment]
these lines are for checking that the load has already been executed

we should fix the reload function which can make the template files be reloaded again

so that you can trigger this manually
