### ISSUE TITLE
automatic escaping in json embed with html template engine

### ISSUE THREAD

**Issue by RaffaeleCu** [gofiber/template#166]
I found out that when i try to embed some json in an html file before serving it to the browser, the json is filled with escape character.

<img width="299" alt="Screenshot 2022-02-25 at 21 30 05" src="https://user-images.githubusercontent.com/64699933/155798095-dbea57d3-e152-4046-b287-7e5fef15bfc6.png">

```go
{
        "Sezioni": {
          "Sezioni": "[{\"id_sezione\":0,\"Titolo_sezione\":\"Introduzione al c++\",\"Riassunto\":\"\",\"Lezioni\":[{\"id\":0,\"Titolo_lezione\":\"Lezione 0 sezione 0\"},{\"id\":1,\"Titolo_lezione\":\"lkjlkj\"}]},{\"id_sezione\":1,\"Titolo_sezione\":\"Preparazione dell'ambiente di sviluppo\",\"Riassunto\":\"\",\"Lezioni\":[{\"id\":0,\"Titolo_lezione\":\"lezione o sezione 1\"}]},{\"id_sezione\":2,\"Titolo_sezione\":\"Introduzione alla gestione dei dati\",\"Riassunto\":\"\",\"Lezioni\":[]},{\"id_sezione\":3,\"Titolo_sezione\":\"Introduzione alle funzioni\",\"Riassunto\":\"\",\"Lezioni\":[]},{\"id_sezione\":4,\"Titolo_sezione\":\"Classi e oggetti\",\"Riassunto\":\"\",\"Lezioni\":[{\"id\":0,\"Titolo_lezione\":\"Lezione 0 id sezione 4\"}]},{\"id_sezione\":5,\"Titolo_sezione\":\"Allocamento dinamico della memoria\",\"Riassunto\":\"\",\"Lezioni\":[]},{\"id_sezione\":6,\"Titolo_sezione\":\"Creazione di un programma semplice\",\"Riassunto\":\"\",\"Lezioni\":[]}]\n"
        }
      }
```

Obviously the client side isn't able to interpret this mess.
However when I print out the json to the terminal it isn't escaped.

<img width="1149" alt="Screenshot 2022-02-25 at 21 34 13" src="https://user-images.githubusercontent.com/64699933/155799080-c82cdaa6-4ba8-4329-8c92-5ec5d5bb2d63.png">

```go
2022/02/25 21:33:26 [{"id_sezione":0,"Titolo_sezione":"Introduzione al c++","Riassunto":"","Lezioni":[{"id":0,"Titolo_lezione":"Lezione 0 sezione 0"},{"id":1,"Titolo_lezione":"lkjlkj"}]},{"id_sezione":1,"Titolo_sezione":"Preparazione dell'ambiente di sviluppo","Riassunto":"","Lezioni":[{"id":0,"Titolo_lezione":"lezione o sezione 1"}]},{"id_sezione":2,"Titolo_sezione":"Introduzione alla gestione dei dati","Riassunto":"","Lezioni":[]},{"id_sezione":3,"Titolo_sezione":"Introduzione alle funzioni","Riassunto":"","Lezioni":[]},{"id_sezione":4,"Titolo_sezione":"Classi e oggetti","Riassunto":"","Lezioni":[{"id":0,"Titolo_lezione":"Lezione 0 id sezione 4"}]},{"id_sezione":5,"Titolo_sezione":"Allocamento dinamico della memoria","Riassunto":"","Lezioni":[]},{"id_sezione":6,"Titolo_sezione":"Creazione di un programma semplice","Riassunto":"","Lezioni":[]}]
```

This should mean that the issue is not in the function that generate the json.

This is the html template:
<img width="432" alt="Screenshot 2022-02-25 at 21 35 49" src="https://user-images.githubusercontent.com/64699933/155799260-dfee6fc5-f1fc-4fc7-9461-62254ee348c8.png">
This is the function in the server side:
<img width="432" alt="Screenshot 2022-02-25 at 21 36 40" src="https://user-images.githubusercontent.com/64699933/155799334-117b3466-f326-40b6-85fa-9b89667f0c2e.png">

```go
func Index(c *fiber.Ctx) error {
	json_response := serv_var.GetSection()
	var buffer bytes.Buffer
	encoder := json.NewEncoder(&buffer)
	//encoder.SetEscapeHTML(false)
	encoder.Encode(&json_response)
	log.Println(string(buffer.String()))
	// Render index template
	return c.Render("index", fiber.Map{
		"json_field": buffer.String(),
	})
	//return c.SendString(buffer.String());
}
```

**Comment by RaffaeleCu** [comment]
@ReneWerner87 
Thanks for your attention.
I read your comment really carefully your response and decided to do some more testing.
In my opinion the test that you conducted does not reflect what I explained in the first first post.

<img width="1440" alt="Screenshot 2022-02-26 at 14 16 45" src="https://user-images.githubusercontent.com/64699933/155844857-2f9cfbc1-1c0c-49b6-8557-2264c54f9c5e.png">
As you can see in the previous Screenshot i didn't change a single line of the original code, however the program work exactly as you would expect.

<img width="1440" alt="Screenshot 2022-02-26 at 14 18 10" src="https://user-images.githubusercontent.com/64699933/155844900-5ed3b2ed-2228-4a22-84b0-df4506b1b1cf.png">
The problem arises when the json is inserted into a <script>.

**Comment by ReneWerner87** [comment]
```go
package main

import (
    "bytes"
    "encoding/json"
    "html/template"
    "log"

    "github.com/gofiber/fiber/v2"
    "github.com/gofiber/template/html"
)


func main() {
    engine := html.New("./assets", ".html")
    app := fiber.New(fiber.Config{Views: engine})

    app.Get("/", func(c *fiber.Ctx) error {
        var buffer bytes.Buffer
        encoder := json.NewEncoder(&buffer)
        encoder.Encode(fiber.Map{"test": "bla"})

        // Render index template
        return c.Render("test", fiber.Map{
            "json_field": template.JS(buffer.String()),
        })
    })

    log.Fatal(app.Listen(":3000"))
}
```
this prevents the automatic escape of the html engine

![image](https://user-images.githubusercontent.com/7063188/155845949-cbe0b794-3c40-48e7-9b48-16c763f0461b.png)
