### ISSUE TITLE
🤗 Html layouts and views, having difficulties and I need help 

### ISSUE THREAD

**Issue by gregg-cbs** [gofiber/template#168]
**Question description**
Can I please have an example of how views and layouts are supposed to interact with each other in Fiber?

At the moment i have set up layouts and views but if I use the layout in more than one view it seems to bug out.

**I have initialised views like so**
_In  my html folder is both my views and layouts_
```go
fApp := fiber.New(fiber.Config{
  Views: html.New("./app/html", ".html"),
})
```

**I made a base layout and in it i define base (as per some example from the internet):**
```go
{{define "base"}}
   <..some html>
  {{template "main" .}}
{{end}}
```

**I use the base template in a view by defining it**
```go
{{template "base" .}}
  {{define "main"}}
     <..some html>
  {{end}}
```

^ this works, but if I used the template again in another view then it shows this view as if something is cross pollinating.

The fiber [docs](https://docs.gofiber.io/guide/templates) on this matter were no help.

**Comment by ReneWerner87** [comment]
@gregg-cbs 

please use the embed tag in every layout and do not define anything yourself
https://github.com/gofiber/template/blob/4b29ea166c3b7f06c9c29bd44f84cd6b9ea65883/html/views/layouts/main.html#L9

our logic will then make sure that your template is rendered into the layout, 
https://github.com/gofiber/template/blob/4b29ea166c3b7f06c9c29bd44f84cd6b9ea65883/html/html.go#L206-L211

like in the example in the readme
https://github.com/gofiber/template/tree/master/html#html

**Comment by gregg-cbs** [comment]
@ReneWerner87 
Thanks for moving this issue.

I have found those docs helpful but with `{{embed}}` approach how do i pass variable to my template?

For example how do I pass the title of the page, previously it was:
```
<title>{{template "title" .}} | Stockr</title>s
```

and in a view that uses the template:
```
{{define "title"}}All Companies{{end}}
```

**Comment by ReneWerner87** [comment]
Template system works independently from this embed tag

The render function must be passed variables which can then be used in layout or in the template which is rendered into the layout.

**Comment by gregg-cbs** [comment]
Thanks, i looked through the html.go and noticed that.

Code for anyone should they come across this:
```go
return c.Render("companies", fiber.Map{
	"MetaTitle": "All Companies",
	"MetaDescription": "Some description",
}, "layouts/base")
```

```
<title>{{.MetaTitle}} | Stockr</title
```

**Comment by gregg-cbs** [comment]
Much appreciated for the quick help! I was lost without you.
