### ISSUE TITLE
this is a bug

### ISSUE THREAD

**Issue by deep-project** [gofiber/template#198]
https://github.com/gofiber/template/blob/1b1a7c7988ea05d870364d4d9770dd73dd726045/jet/jet.go#L209

Should be
`if e.reload {
	e.reload = false
}`

**Comment by ReneWerner87** [comment]
no it is correct, if reload is true load should be set to false just before the load command

**Comment by deep-project** [comment]
> no it is correct, if reload is true load should be set to false just before the load command

Are you sure? If e.reload is not set to false, it will always remain true, And will always be reload.

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/template/blob/c57f5fb4fcf37dfbe8328106647e5f49d294a7a1/jet/jet.go#L103
