### ISSUE TITLE
Pongo2 addfunc is apparently not getting injected during templates rendering

### ISSUE THREAD

**Issue by ansrivas** [gofiber/template#20]
Hi, thank you for creating this project and especially the latest new feature with `pkger` etc.

I was testing with adding functions to django/pongo2 templates but seems its not working. Just for the sake of reproduction I have added a simple pull request with corresponding test here  #19

**Comment by Fenny** [comment]
@ansrivas thank you for your PR, version `v1.5.2` is tagged 👍

**Comment by ansrivas** [comment]
Thank you so much. Closing it.
