### ISSUE TITLE
Tag new version of django/v3?

### ISSUE THREAD

**Issue by iredmail** [gofiber/template#244]
Dear developers,

Current django/v3 upgrades pongo2 from v4 to v6, it's a good time to tag a new version of django/v3 so that fiber users can use pongo2 v6.

**Comment by ReneWerner87** [comment]
sure had it in the back of my mind, then forgot again
you can trigger me next time also about dicord an

first wanted to see how the multi release concept works here

-> will release right away

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/template/releases/tag/django%2Fv3.0.0

**Comment by iredmail** [comment]
Thanks @ReneWerner87 :)
