### ISSUE TITLE
[Improvement]: 🚀 Interface for the template engines

### ISSUE THREAD

**Issue by ReneWerner87** [gofiber/template#248]
To make sure that all template engines have the same interface and thus core functionalities, we should create an interface
example:
https://github.com/gofiber/fiber/blob/6770e45590fecea4c43a749e374c73868638a4d1/ctx.go#L139-L142

How should we handle breaking changes ?
Maybe we should provide the interfaces with versions suffixes or prefixes
Since it is possible to have different versions through the multi release repository, we should find a solution for the different major versions

This should prevent features from being forgotten in other eniges
https://github.com/gofiber/template/pull/241

**Comment by mfiumara** [comment]
Hey I thought I gave this a shot.

I've added an example for the pug templating engine on how it would look like with an interface, please check https://github.com/mfiumara/template/commit/7e672490eb207ccfeb9aa74fdabc88978bf5bd38.
