### ISSUE TITLE
What is the easiest way to make ajax-like call from web page to fiber api

### ISSUE THREAD

**Issue by slusarczyk41** [gofiber/template#25]
Generaly speaking, I want to retrieve data from a server without reloading a page. I guess I can write a javascript code with something like `get('fiber_api_route/get_data')` and include it in html template. Is there a better way to do is without a need to write js code? The desired way of doing this is to add to html template something like `<button onClick=golang_fiber_function!_name>`.
Have a great day
Jacek

**Comment by Fenny** [comment]
Hi @slusarczyk41, you could use HTML5 pushState and render HTML on the server 👍
