### ISSUE TITLE
🐛 [Bug]: 

### ISSUE THREAD

**Issue by rngallen** [gofiber/template#266]
### Bug Description

`go get github.com/gofiber/template/html` does not work as expected

 github.com/gofiber/template/html: module github.com/gofiber/template@latest found (v1.8.2), but does not contain package github.com/gofiber/template/html

### How to Reproduce

just a basic figer app

### Expected Behavior

it was supposed to download library from github

### Template package Version

2.0.3

### Code Snippet (optional)

```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/template/html"
)

func main() {

	engine := html.New("./layouts", ".html")

	app := fiber.New(fiber.Config{
		Views: engine,
	})

	log.Fatal(app.Listen(":3030"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by efectn** [comment]
Use this: github.com/gofiber/template/html/v2

**Comment by rngallen** [comment]
Thanks, it work

It should be fixed on official doc too. [https://docs.gofiber.io/guide/templates](url)
