### ISSUE TITLE
🐛 [Bug]: v1.8.2 appears to be missing github.com/gofiber/template/html

### ISSUE THREAD

**Issue by arunsworld** [gofiber/template#271]
### Bug Description

Using the latest released version (v1.8.2) for "github.com/gofiber/template/html" results in the below error:
github.com/gofiber/template/html: module github.com/gofiber/template@latest found (v1.8.2), but does not contain package github.com/gofiber/template/html

v.1.8.1 is just fine. Haven't investigated further into the changelogs to understand the cause but I don't believe this is expected?

### How to Reproduce

1. Create a new project that uses "github.com/gofiber/template/html"
2. Or update an existing one to v.1.8.2
3. Run "go mod tidy"

### Expected Behavior

go mod tidy should succeed.

### Template package Version

v.1.8.2

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by efectn** [comment]
Use `github.com/gofiber/template/html/v2` instead

**Comment by arunsworld** [comment]
Thanks a lot! That worked. Sorry if I missed some documentation regarding this change.
