### ISSUE TITLE
Function after render

### ISSUE THREAD

**Issue by fuadarradhi** [gofiber/template#28]
is there a function that is executed after template rendering?, for example to minify html

**Comment by Fenny** [comment]
You can use the interface it provides, it's the actual method used by Fiber internals see [ctx.go#L808](https://github.com/gofiber/fiber/blob/master/ctx.go#L808)
```go
buf := bytebufferpool.Get()
defer bytebufferpool.Put(buf)

if err := app.Settings.Views.Render(buf, "index", fiber.Map{}); err != nil {
    return err
}

// Rendered template is now available
// buf.Bytes()
```

**Comment by fuadarradhi** [comment]
okay, thanks for the clue,
it seems to be easier if I change the template engine i used so that it supports the after rendering function

**Comment by Fenny** [comment]
Possibilities are endless 👍 
```go
engine := html.New("./views", ".html")

buf := bytebufferpool.Get()
if err := engine.Render(buf, "index", fiber.Map{}); err != nil {
    return err
}
html := minifiy(buf.Bytes())
bytebufferpool.Put(buf)
```

**Comment by fuadarradhi** [comment]
thanks, i do this to simplify,
`engine.AfterRender(func(html string) string){
    return minify(html)
}`

**Comment by BellZaph** [comment]
> thanks, i do this to simplify,
> `engine.AfterRender(func(html string) string){ return minify(html) }`

can u share this code about AfterRender, sounds interesting
