### ISSUE TITLE
🐛 [Bug]: Django (pongo2) integration vulnerability to XSS

### ISSUE THREAD

**Issue by bastianwegge** [gofiber/template#281]
### Bug Description

Currently inside of pongo2 there's a setting that sets `pongo2.SetAutoescape(false)` which disables HTML sanitization, as far as I can see. This makes the gofiber/template/django integration unusable for my project.

### How to Reproduce

1. Create a basic project including gofiber + gofiber/template/django
2. Create a variable with a string `<script>alert("ALERTAAAA");</script>`
3. Print the variable into a template
4. You have a potential XSS attack if the variable was created by user-input

### Expected Behavior

I'd expect HTML sanitization to be active at all times. I'd also expect some documentation on how to explicitly deactivate sanitization for a non-user-input variable that is able to render valid HTML.

### Template package Version

Django - v3.1.5

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by gaby** [comment]
We could add a config value for this, would that work for you @bastianwegge ?

**Comment by sixcolors** [comment]
@gaby shouldn't we set it to true?

**Comment by gaby** [comment]
@sixcolors I'd say yes

**Comment by sixcolors** [comment]
> @sixcolors I'd say yes. Is there a use case for having this disable?

Not sure. I’ll have to read pnogo2 docs. There are valid reasons to allow unsafe. But I don’t know why you would do it globally. Unless it doesn’t have a way to do it selectively.

**Comment by gaby** [comment]
@sixcolors It only works per template or globally. https://github.com/flosch/pongo2/issues/312

We can add it as a config variable, and enable it by default

**Comment by sixcolors** [comment]
So docs are non existent for pongo2. But https://github.com/flosch/pongo2/blob/c84aecb5fa79a9c0feec284a7bf4f0536c6a6e99/template_tests/autoescape.tpl suggests it can be done in the template. 

I would set it to true in the django.go and let them use disable in the template.

we could add a config option or not. But secure by default on templates would be my preference.

**Comment by gaby** [comment]
@sixcolors Agree! I will work on a PR

**Comment by bastianwegge** [comment]
Hey @gaby, we went with something completely different because of the security issues. Rene suggested to open an issue so this wouldn't go unnoticed.

**Comment by gaby** [comment]
I plan on updating all the unit-tests today. The output is quite different that without escaping!

**Comment by sixcolors** [comment]
Could be in the way the template is passed in. I’ll take a look when I get off work. On Jan 8, 2024, at 10:27 AM, Juan Calderon-Perez ***@***.***> wrote:﻿
I plan on updating all the unit-tests today. The output is quite different that without escaping!
