### ISSUE TITLE
🤗 [Question]: How can i divide my layout, component and views folders

### ISSUE THREAD

**Issue by Necoo33** [gofiber/template#282]
### Question Description

Hello, i want to know how to structure my code with the way that components, layouts and pages/views are individual folders in same directory. 

It would be great if you do necessary changes on the following code:

```go

package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/template/html/v2"
)

func main() {
	htmlFiles := html.New("./pages", ".html")
	htmlFiles.Reload(true)

	server := fiber.New(fiber.Config{
		Views: htmlFiles,
	})

	server.Get("/", func(context *fiber.Ctx) error {
		return context.Render("home", fiber.Map{
			"Data": "Hello",
		})
	})

	server.Listen(":2000")
}

```

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/template/%package%"

func main() {
  // Steps to reproduce
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
you can do it like in our example projects
https://github.com/gofiber/recipes/tree/master/template

**Comment by Necoo33** [comment]
> you can do it like in our example projects
> https://github.com/gofiber/recipes/tree/master/template

I want to make all the three folders in same three level on the root directory like this:

components
pages
layouts
mainpoint(main package exist int here)
go.work
go.sum

**Comment by ReneWerner87** [comment]
You can use the root folder as view folder
since we have the extension in the engine, all files that do not match the extension will be skipped

**Comment by Necoo33** [comment]
> You can use the root folder as view folder since we have the extension in the engine, all files that do not match the extension will be skipped

Thanks, it worked. I think you should consider allowing to put layout and view folders in the root directory without setting root folder of engine as view folder.
