### ISSUE TITLE
How to change layout Title 

### ISSUE THREAD

**Issue by suntong** [gofiber/template#31]
I want my `layout` to be a template for all my pages. However the 

```go
c.Render("index", fiber.Map{
            "Title": "Hello, World!",
        })
```

Can only change the content _within_ `body`. 

I need to change the HTML Title in the header as well. 
Any way to do that? thx.

**Comment by suntong** [comment]
I first drafted this question here, but asked in fiber eventually. 

However, having close it on fiber, and thinking back, I think this is still an valid question/issue -- people need their layout to be a template for _all_ their pages, and they need to change the HTML Title for _every_ page. 

So, would be OK that I change the default html template to satisfy this, so that the next people won't need to wonder again? If I did so, would you accept the PR?

**Comment by suntong** [comment]
I actually, I _**thought**_ I could make it work, but I wasn't able to. So this still remains as a question first.

**Comment by BellZaph** [comment]
So, do u know how to set variables in several places?

**Comment by suntong** [comment]
Hi @Fenny,

Please advice -- now it is more than me facing the same problem. (I kind of solve it a hacky way, but don't want to miss-lead people).

**Comment by thomasvvugt** [comment]
May I ask what template engine you are using? From my previous experience, I can tell that `handlebars` was replacing variables in any part of the view.

**Comment by BellZaph** [comment]
> May I ask what template engine you are using? From my previous experience, I can tell that `handlebars` was replacing variables in any part of the view.

django

**Comment by thomasvvugt** [comment]
Hi @suntong and @BellZaph, rendering templates using the `django` engine seems to work fine on my end.
Can you provide a minimal code example to reproduce this issue? See my code examples below.

main.go
```go
package main

import (
	"github.com/gofiber/fiber"
	"github.com/gofiber/template/django"
)

func main() {
	engine := django.New("./views", ".django")

	// Pass the engine to the Views
	app := fiber.New(&fiber.Settings{
		Views: engine,
	})

	app.Get("/", func(c *fiber.Ctx) {
		// Render index
		_ = c.Render("index", fiber.Map{
			"Title": "Index!",
		})
	})

	_ = app.Listen(8080)
}
```

views/index.django
```
<!DOCTYPE html>
<html>

<head>
  <title>{{ Title }}</title>
</head>

<body>
  <h1>{{ Title }}</h1>
</body>

</html>
```

Thanks for bringing up the issue! 🚀

**Comment by suntong** [comment]
Thanks for the working demo for @BellZaph, @thomasvvugt. 

My question was for html template, to be specifically, about these lines

https://github.com/gofiber/template/blob/a06b81ac329a67bb95e9db5f6df78428f4e84f21/html/views/layouts/main.html#L4-L6

I.e., how to change the `Title` for the **layout file**. Thx.

**Comment by fuadarradhi** [comment]
for global, use function engine

```go
engine.AddFunc("title", func() string {
    return "this is title"
})
```

```html
<head> 
   <title>{{ title() }}</title> 
 </head>
```

**Comment by suntong** [comment]
Thanks! 

If that's the only solution, then I think my hacky one is better, :)
But still, because it is really hacky, I want to make sure there is no more better options first.

**Comment by thomasvvugt** [comment]
Hi @suntong, the `html` package can also context with provided data, see; https://golang.org/pkg/html/template/

The example @fuadarradhi showed can be simplified by using the `{{.}}` parameters;

_main.go_
```go
package main

import (
	"github.com/gofiber/fiber"
	"github.com/gofiber/template/html"
)

func main() {
	engine := html.New("./views", ".html")

	app := fiber.New(&fiber.Settings{
		Views: engine,
	})

	app.Get("/", func(c *fiber.Ctx) {
		// Render index
		c.Render("index", fiber.Map{
			"Title": "Index!",
		})
	})

	app.Listen(8080)
}
```

_views/index.html_
```html
<!DOCTYPE html>
<html>

<head>
    <title>{{ .Title }}</title>
</head>

<body>
<h1>{{ .Title }}</h1>
</body>

</html>
```

Keep in mind: HTML templates treat data values as plain text which should be encoded so they can be safely embedded in an HTML document. The escaping is contextual, so actions can appear within JavaScript, CSS, and URI contexts. 

You should **always** escape your data if not already sanitized, the HTML templates provides several functions for this; https://golang.org/pkg/html/template/#hdr-Contexts

Once again, thanks for bringing up the issue. Let me know if my example helps you out or leaves you with additional questions! 🔥

**Comment by BellZaph** [comment]
Hey guys
Thanks for answer
I thought it works different than original Django/template
Now all fine

**Comment by suntong** [comment]
> Thanks for the working demo for @BellZaph, @thomasvvugt.
> 
> My question was for html template, to be specifically, about these lines
> 
> https://github.com/gofiber/template/blob/a06b81ac329a67bb95e9db5f6df78428f4e84f21/html/views/layouts/main.html#L4-L6
> 
> I.e., how to change the `Title` for the **layout file**. Thx.

Hmm... let me stress again that my question is 

how to change the `Title` for the **layout file**

yet, @thomasvvugt, both of your demo code are _not_ using the **layout file**. So let me be specific

_**./views/index.html**_
```html
{{template "partials/header" .}}

<h1>{{.Title}}</h1>

{{template "partials/footer" .}}
```
_**./views/partials/header.html**_
```html
<h2>Header</h2>
```
_**./views/partials/footer.html**_
```html
<h2>Footer</h2>
```
_**./views/layouts/main.html**_
```html
<!DOCTYPE html>
<html>

<head>
  <title>Main</title>
</head>

<body>
  {{embed}}
</body>

</html>
```

```go
package main

import (
	"github.com/gofiber/fiber"
	"github.com/gofiber/template/html"
)

func main() {
	// Create a new engine
	engine := html.New("./views", ".html")

	// Pass the engine to the Views
	app := fiber.New(&fiber.Settings{
		Views: engine,
	})

	app.Get("/", func(c *fiber.Ctx) {
		// Render index
		c.Render("index", fiber.Map{
			"Title": "Hello, World!",
		})
	})

	app.Get("/layout", func(c *fiber.Ctx) {
		// Render index within layouts/main
		c.Render("index", fiber.Map{
			"Title": "Hello, World!",
		}, "layouts/main")
	})

	app.Listen(3000)
}

```

The two `app.Get` above, one is using  **layout file** and one is not. my question is how to change the `Title` for the **layout file**. I.e., the piece called with

```go
	app.Get("/layout", func(c *fiber.Ctx) {
		// Render index within layouts/main
		c.Render("index", fiber.Map{
			"Title": "Hello, World!",
		}, "layouts/main")
```

thx

**Comment by fuadarradhi** [comment]
@suntong 
for single route, changing the layout file is the same as changing the body,
my previous example is for global route, if you not want pass title for every route

```html
<!DOCTYPE html>
<html>

<head>
  <title>{{.Title}}</title>
</head>

<body>
  {{embed}}
</body>

</html>
```

**Comment by suntong** [comment]
wow, I should have tried -- I thought it is not possible, and now I'm embarrassed, :).

**Comment by edimoldovan** [comment]
Is this above still a valid solution? I am passing PageTitle but my render fails with this error

```views: Parse error on line 7:
Expecting ID, got: 'Sep{"."}'```

Relevant hbs code
```<title>{{.PageTitle}}</title>```

and the corresponding route 
```app.Get("/", func(c *fiber.Ctx) error {
		// Render index within layouts/main
		return c.Render("index", fiber.Map{
			"Title":     "relee.se",
			"PageTitle": "relee.se blog",
		}, "layouts/main")
	})```

**Comment by suntong** [comment]
What's your views file of line 7?

**Comment by edimoldovan** [comment]
@suntong This is my view

```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{{ .Title }}</title>
  <meta name="description" content="Writing about releasing. Among other things.">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="/public/favicon.png">
  <link rel="stylesheet" href="/public/style.min.css">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet"> 
</head>
<body>
  <div id="wrapper" class="wrapper">
    {{embed}}
  </div>
</body>
</html>
```
