### ISSUE TITLE
🐛 [Bug]: Module doesnt contain package

### ISSUE THREAD

**Issue by kashingonline** [gofiber/template#318]
### Bug Description

github.com/gofiber/template/html: module github.com/gofiber/template@latest found (v1.8.2), but does not contain package github.com/gofiber/template/html

### How to Reproduce

go mod tidy

### Expected Behavior

I ekxpect it to install

### Template package Version

1.8.2

### Code Snippet (optional)

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/monitor"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/template/html"
)

func NewApplication() *fiber.App {
	env.SetupEnvFile()
	//database.SetupDatabase()
	engine := html.New("./views", ".html")
	app := fiber.New(fiber.Config{Views: engine})
	app.Use(recover.New())
	app.Use(logger.New())
	app.Get("/dashboard", monitor.New())
	router.InstallRouter(app)

	return app
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
Pls check the docs and use version 2

https://docs.gofiber.io/template/html/

**Comment by gaby** [comment]
@kashingonline Does the above fix your issue?
