### ISSUE TITLE
🤗 [Question]: Why Mustache was excluded from the extended benchmark

### ISSUE THREAD

**Issue by jefer94** [gofiber/template#320]
### Question Description

I just want to know the reason of that decision, and this issue should be related to the documentation of this project

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@jefer94 Basically some of the templates don't have an extended templated used during testing, only a simple one. Slim is another template like Mustache that doesn't have an extended example.

**Comment by jefer94** [comment]
Ok it is not related to the capabilities of the template engine, is useful to know it

**Comment by gaby** [comment]
@jefer94 Correct, it's not related to the capabilities of the template engine.
