### ISSUE TITLE
🐛 [Bug]: Jet, inside {{ embed() }} no error propagation

### ISSUE THREAD

**Issue by iacore** [gofiber/template#341]
### Bug Description

https://github.com/gofiber/template/issues/339#issuecomment-1951440680

### How to Reproduce

https://github.com/iacore/debug-gofiber-jet-no-error

### Expected Behavior

show error pls

### Template package Version

see in repro repo

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by gaby** [comment]
@iacore I'd be looking at this during the weekend

**Comment by gaby** [comment]
Fixed via #365 
Released in https://github.com/gofiber/template/releases/tag/jet%2Fv2.1.9
