### ISSUE TITLE
🐛 [Bug]: Template layout always show last loaded page.

### ISSUE THREAD

**Issue by jiuliyemingzhi** [gofiber/template#361]
### Bug Description

Template layout always show last loaded page, I defined a layout template and some normal template they have similar struction.
```html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{{.Title}}</title>

	<link rel="stylesheet" type="text/css" href="all.min.css">
	{{block "page-css" .}}{{end}}
</head>

<body>

{{block "main" .}}{{end}}

<script src="assets/js/all.min.js"></script>
{{block "page-js" .}}{{end}}
</body>
</html>
```

### How to Reproduce

https://github.com/jiuliyemingzhi/fiber-tmpl-problem
1.go run main.go
2.click to open 127.0.0.1:3000 in browser

### Expected Behavior

I think this page should show current url target page.

### Template package Version

v2.1.1

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/template/%package%"

func main() {
  	engine := html.New(conf.StaticPath, ".html")
	engine.Debug(true)
	engine.Reload(conf.Debug)
	app := fiber.New(fiber.Config{
		Views:     engine,
		BodyLimit: 2 * 1024 * 1024,
	})
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
pls use our layout approach with the {{embed}} tag
https://github.com/gofiber/template/tree/master/html#basic-example

**Comment by jiuliyemingzhi** [comment]
> pls use our layout approach with the {{embed}} tag https://github.com/gofiber/template/tree/master/html#basic-example @jiuliyemingzhi

Thinks，I know this  but I have a more complex usage scenarios。So {{embed}} meet the demand。 Like this code
```html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{{.Title}}</title>

	<link rel="stylesheet" type="text/css" href="all.min.css">
	{{block "page-css" .}}{{end}}
</head>

<body>

{{block "main" .}}{{end}}

<script src="assets/js/all.min.js"></script>
{{block "page-js" .}}{{end}}
</body>
</html>
```

**Comment by sixcolors** [comment]
To clarify. This is not a caching problem where the last rendered template is being re-rendered. The issue is that "main" has been redefined in various files in `./templates`, and all of them are being parsed by the views engine in `app`.

For instance, I added a file to your example app: 

![Image 2024-03-10 at 3 32 PM](https://github.com/gofiber/template/assets/6501251/d9563eed-fd4a-4371-bfcb-9f2318d23ed1)

I see two possible solutions to address the use case reported:

1. Use the `{{embed}}` tag to load different content in a layout with the Fiber `Render()` function.

2. Use `html/template` independently of Fiber to limit which file is parsed by the template, which will be slower without caching etc, but prevents "main" from being redefined by other files.

Example for solution 2:

```go
package main

import (
	"bytes"
	"html/template"
	"log"
	"path/filepath"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New(fiber.Config{})

	app.Get("/", func(ctx *fiber.Ctx) error {
		return ctx.Redirect("/index2.html")
	})
	app.Get("/:page", func(ctx *fiber.Ctx) error {
		page := ctx.Params("page", "index1.thml")

		// Clean the page parameter and join it with the template directory
		pagePath := filepath.Join("template", filepath.Clean("/"+page))

		tmpl, err := template.ParseFiles("template/layout.html", pagePath)
		if err != nil {
			return ctx.Status(404).SendString("404 Not Found")
		}

		var buf bytes.Buffer

		err = tmpl.Execute(&buf, map[string]interface{}{})
		if err != nil {
			log.Println("Template execution error:", err)
			return ctx.Status(fiber.StatusInternalServerError).SendString("Internal Server Error")
		}
		ctx.Response().Header.SetContentType(fiber.MIMETextHTMLCharsetUTF8)
		return ctx.Status(fiber.StatusOK).Send(buf.Bytes())
	})
	log.Fatal(app.Listen(":3000"))
}
```

@jiuliyemingzhi hope that helps.

@ReneWerner87, I think that this is not a bug, but rather an implementation detail that reflects the behaviour of the `html/template` `ParseFiles()` function. To avoid confusion, it would be helpful to update the documentation to explain that templates read during `Load()` are loaded when the app is initialized, and the use case mentioned by @jiuliyemingzhi is not supported.

**Comment by jiuliyemingzhi** [comment]
> To clarify. This is not a caching problem where the last rendered template is being re-rendered. The issue is that "main" has been redefined in various files in `./templates`, and all of them are being parsed by the views engine in `app`.
> 
> For instance, I added a file to your example app:
> 
> ![Image 2024-03-10 at 3 32 PM](https://private-user-images.githubusercontent.com/6501251/311535894-d9563eed-fd4a-4371-bfcb-9f2318d23ed1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMDY1NDksIm5iZiI6MTcxMDEwNjI0OSwicGF0aCI6Ii82NTAxMjUxLzMxMTUzNTg5NC1kOTU2M2VlZC1mZDRhLTQzNzEtYmZjYi05ZjIzMThkMjNlZDEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTBUMjEzMDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmFlODY5NWEwMTMzM2MyMGQ2ZjlkNDRjYzlkNjQ3OGEyODNjMzdmNmYzOWVhMmE2YTkxMzJmZWRlNTBiNGNhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3LaTOvNT9ijKQ2dSYPmrkyfVPRHJa5qqpyZrTuaIVRE)
> 
> I see two possible solutions to address the use case reported:
> 
> 1. Use the `{{embed}}` tag to load different content in a layout with the Fiber `Render()` function. Define other dynamic, used in each template, content in go not the html templates.
> 2. Use `html/template` independently of Fiber to limit which file is parsed by the template, which will be slower without caching etc, but prevents "main" from being redefined by other files.
> 
> Example for solution 2:
> 
> ```go
> package main
> 
> import (
> 	"bytes"
> 	"html/template"
> 	"log"
> 	"path/filepath"
> 
> 	"github.com/gofiber/fiber/v2"
> )
> 
> func main() {
> 	app := fiber.New(fiber.Config{})
> 
> 	app.Get("/", func(ctx *fiber.Ctx) error {
> 		return ctx.Redirect("/index2.html")
> 	})
> 	app.Get("/:page", func(ctx *fiber.Ctx) error {
> 		page := ctx.Params("page", "index1.thml")
> 
> 		// Clean the page parameter and join it with the template directory
> 		pagePath := filepath.Join("template", filepath.Clean("/"+page))
> 
> 		tmpl, err := template.ParseFiles("template/layout.html", pagePath)
> 		if err != nil {
> 			return ctx.Status(404).SendString("404 Not Found")
> 		}
> 
> 		var buf bytes.Buffer
> 
> 		err = tmpl.Execute(&buf, map[string]interface{}{})
> 		if err != nil {
> 			log.Println("Template execution error:", err)
> 			return ctx.Status(fiber.StatusInternalServerError).SendString("Internal Server Error")
> 		}
> 		ctx.Response().Header.SetContentType(fiber.MIMETextHTMLCharsetUTF8)
> 		return ctx.Status(fiber.StatusOK).Send(buf.Bytes())
> 	})
> 	log.Fatal(app.Listen(":3000"))
> }
> ```
> 
> @jiuliyemingzhi hope that helps.
> 
> @ReneWerner87, I think that this is not a bug, but rather an implementation detail that reflects the behaviour of the `html/template` `ParseFiles()` function. To avoid confusion, it would be helpful to update the documentation to explain that templates read during `Load()` are loaded when the app is initialized, and the use case mentioned by @jiuliyemingzhi is not supported.

## Thinks! That solved my problem.

**Comment by ReneWerner87** [comment]
Yes right, the engine loads all files and renders them and then definitions with the same names are overwritten

That was the reason why I meant the embed layout 

But right, with more explanations it offers more acceptance
