### ISSUE TITLE
🤗 [Question]: How do I render conditionals in Pug

### ISSUE THREAD

**Issue by AxelRHD** [gofiber/template#393]
### Question Description

I really love to see that Fiber is supporting Pug for templates.

Just fiddling around but I can't get a simple example to work.

Title is working, the conditional not.

Rendering in handler:

```go
app.Get("/hello", func(c *fiber.Ctx) error {
        return c.Render("hello", fiber.Map{
                "Title":    "Hello from Fiber with Pug!",
                "LoggedIn": true,
        })
})
```

Getting the following warning: `2024/08/29 23:47:08.480286 app.go:999: [Warn] failed to load views: template: hello:2: unexpected "#" in if`

### Code Snippet (optional)

```go
h1.title #{ .Title }

if #{ .LoggedIn }
  p Hello User!
else
  p Hello Stranger!
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by AxelRHD** [comment]
This one is also not working:

```pug
- var loggedIn = #{ .LoggedIn }
h1.title #{ .Title }

if loggedIn
        p Hello User!
else
        p Hello Stranger!
```

**Comment by AxelRHD** [comment]
Sometimes it is simpler than expected:

```pug
h1.title #{ .Title }

if .LoggedIn
  p Hello User!
else
  p Hello Stranger!
```

Maybe a short example can be added to the documentation?

**Comment by efectn** [comment]
> Sometimes it is simpler than expected:
> 
> ```
> h1.title #{ .Title }
> 
> if .LoggedIn
>   p Hello User!
> else
>   p Hello Stranger!
> ```
> 
> Maybe a short example can be added to the documentation?

Sure, you can create a PR to demonstrate Pug syntax and behavior in docs
