### ISSUE TITLE
Template Rendering Incorrectly

### ISSUE THREAD

**Issue by keiranrowan** [gofiber/template#65]
Using the "template/html" package I am having issues rendering templates that derive a base layout all located in the same directory. I have a base layout template like so:

base.html
```html
{{define "base"}}
<!DOCTYPE html>
<html lang="en">
<body>

header...

{{block "content" .}}{{ end }}

footer...

</body>
</html>
{{end}}
```

a first page like so which renders fine:

first.html
```html
{{ template "base" .}}

{{define "content"}}
Some content
{{end}}
```

and a second page like so:

second.html
```html
{{ template "base" .}}

{{define "content"}}
Some more content
{{end}}
```
My template configuration looks as follows:
```go
    engine := html.New("./views", ".html")
    engine.Reload(true)

    app := fiber.New(fiber.Config{
        Views: engine,
    })

    app.Get("/first", func(c *fiber.Ctx) error {
        return c.Render("first", fiber.Map{})
    })

    app.Get("/second", func(c *fiber.Ctx) error {
        return c.Render("second", fiber.Map{})
    })
```
The issue I am encountering is that the second page renders the content of the first. Is this expected behavior in this situation? Normally with "template/html" I would call ```template.ParseFiles("first.html", "base.html")``` for the first template and ```template.ParseFiles("second.html", "base.html")``` for the second template. How exactly does Fiber determine which templates to parse based on the single template name? Thanks!

**Comment by dorianim** [comment]
Hi,

I have the same issue. Has this been resolved?

**Comment by buroz** [comment]
I got the same issue now. Anyone solved?

**Comment by ospng** [comment]
Hi, I got the same issue, any solutions for that?
