### ISSUE TITLE
Why call pongo2 style template django?

### ISSUE THREAD

**Issue by kmpm** [gofiber/template#68]
Why call pongo2 style template django? 
The readme for pongo2 says..
> pongo2 is a Django-syntax __LIKE__ templating-language.

(emphasis mine)
Since the syntax is not 100% alike I would rather not have to look for what libraries that is actually used for the django like syntax.
Just calling it pongo2 would be much more descriptive but I might have missed something.

**Comment by Fenny** [comment]
I personally do not have a lot of experience with the django template engine, I could not find another engine in Go that is based on django syntax. That's the reason we named it Django, but I'm open for replacing it with a better library.
