### ISSUE TITLE
Loading Assets from manifest.json

### ISSUE THREAD

**Issue by Benozo** [gofiber/template#83]
Hi 

I'm in the hunt of a best approach to add assets from build tools like webpack or Vite into the templates.

Most assets are bundled with assets tagged with version e.g index.12345678890.js and is mapped from within the manifest.json file .

And I would like to reference an asset like {{ asset eq "index.js" }}  or {{ asset eq "main.css" }} which reads the manifest.json and adds the correct asset to the template .

**Comment by husi-dev** [comment]
ohh my bad, just found Addfunc()

**Comment by Benozo** [comment]
AddFunc()  would do it :-)
