### ISSUE TITLE
django: unable to resolve template

### ISSUE THREAD

**Issue by iredmail** [gofiber/template#94]
Django engine (pongo2) can not resolve the layout template file with the sample code in this repo. Here's how to reproduce it.

Tested environments

1. Ubuntu 18.04 (x86_64), Go 1.16
2. macOS 11.2.2, Go 1.16

```
$ git clone --depth=1 git@github.com:gofiber/recipes.git
$ cd recipes/template/
$ go mod vendor && go mod download && go mod tidy
$ cd django/
$ go run main.go 
views: [Error (where: fromfile) in ./layouts/main1.html] unable to resolve template

 ┌───────────────────────────────────────────────────┐
 │                    Fiber v2.0.1                   │
 │               http://127.0.0.1:3000               │
 │                                                   │
 │ Handlers ............. 4  Threads ............. 1 │
 │ Prefork ....... Disabled  PID .............. 3073 │
 └───────────────────────────────────────────────────┘
```

If i changed the first in `views/index.html` from `{% extends "./layouts/main1.html" %}` to `{% extends "./views/layouts/main1.html" %}`, then it works. But since we have `django.New("./views", ".html")` in `main.go`, isn't it expected that pongo2 looks for files under `views/` directory and no need to write this directory name in the `extends` tag?

Also, with the modified working template file (`{% extends "./views/layouts/main1.html" %}`), it failed with `embed` package. Sample code below:

```
package main

import (
        "embed"
        "log"
        "net/http"

        "github.com/gofiber/fiber/v2"
        "github.com/gofiber/template/django"
)

//go:embed views/*
var embedDirViews embed.FS

func main() {

        // Create a new engine
        // engine := django.New("./views", ".html")
        engine := django.NewFileSystem(http.FS(embedDirViews), ".html")

        // Or from an embedded system
        // See github.com/gofiber/embed for examples
        // engine := html.NewFileSystem(http.Dir("./views", ".django"))

        // Pass the engine to the Views
        app := fiber.New(fiber.Config{
                Views: engine,
        })

        app.Get("/", func(c *fiber.Ctx) error {
                // Render with and extends
                return c.Render("index", fiber.Map{
                        "Title": "Hello, World!",
                })

        app.Get("/embed", func(c *fiber.Ctx) error {
                // Render index within layouts/main
                return c.Render("embed", fiber.Map{
                        "Title": "Hello, World!",
                }, "layouts/main2")
        })

        log.Fatal(app.Listen(":3000"))
}
```

No matter how i changed the path in `extends` tag, always error like this:

```
views: [Error (where: fromfile) in ./views/layouts/main1.html] unable to resolve template
```

**Comment by iredmail** [comment]
Spent 2 days on this issue, and i managed to "fix" it:

https://github.com/gofiber/template/blob/master/django/django.go#L126
`MustNewHttpFileSystemLoader` should receive empty string as value of `baseDir`.

```
# Current code, and NOT work.
		pongoloader = pongo2.MustNewHttpFileSystemLoader(e.fileSystem, baseDir)

# Should be changed to:
		pongoloader = pongo2.MustNewHttpFileSystemLoader(e.fileSystem, "")
```

**Comment by ly020044** [comment]
Is it sufficient to use relative paths in the file system?

**Comment by iredmail** [comment]
Dear @ReneWerner87,

Could you please help review and hopefully merge this PR? Thank you very much.

**Comment by ReneWerner87** [comment]
Yes, I'm already on it, but I still have to do a few tests and these need time

**Comment by ReneWerner87** [comment]
will come with the next release

**Comment by iredmail** [comment]
Dear @ReneWerner87 

Would you mind tagging a new version of `fiber/template`? :)

**Comment by ReneWerner87** [comment]
we will release in the next few days and hopefully faster and more often in the future.

**Comment by iredmail** [comment]
I hope there's a new small minor release when we get some issue fixed. 1.6.x is ok, but 1.6.6.x is ok too. haha :)

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/template/releases/tag/v1.6.7

**Comment by SharkFourSix** [comment]
This isn't working for me. So I had to create a local copy of django.go and pass the the directory of my embedded views into django.NewFileSystem, which also get passed to pongo2.MustNewHttpFileSystemLoader as ```pongo2.MustNewHttpFileSystemLoader(e.fileSystem, baseDir)```

I would suggest making a fix and add a flag (default to false for backwards compatibility) to make passing the base path optional.
